# Version of Docker-compose
version: '3.8'
services:
  # Service name
  node:
    # Creating a custom image
    build:
      # Location to the Dockerfile
      context: .
      # Name of the Dockerfile
    ports:
        # External port:Internal port
      - 8080:8080
    # Environment variables
    environment:
      - NODE_ENV=development
    # Command to run
    command: "npm start"

